
python: 3.7

branches:
  only:
    - master

before_install:
  - "./.travis/install.sh"

# see macOS version https://docs.travis-ci.com/user/reference/osx/#os-x-version

matrix:
  include:
  - os: osx
    osx_image: xcode11.3  # 10.14 on travis
    language: generic
    script:
    - "./.travis/tests.sh"


after_failure:
  - lftp -e "mirror -R ./tests/tempTestData $FTP_REMOTE_DIR" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST

after_success:
  - codecov
